stages:
  # a_get_data_service: 
  #   cmd: python ${project_dir}src/loan_velocity/get_data.py --config=params.yaml
  #   always_changed: true
  #   deps:
  #   - ${project_dir}src/loan_velocity/get_data.py
  #   - ${project_dir}data/raw/loan_velocity_raw_bloom1.parquet
  #   - ${project_dir}data/raw/loan_velocity_raw_bloom2.parquet
  #   - ${project_dir}data/raw/loan_velocity_raw_solv.parquet
  #   - ${project_dir}data/raw/loan_velocity_raw_tanda.parquet
  #   - ${project_dir}data/raw/loan_velocity_raw_copia.parquet
  #   - ${project_dir}data/raw/loan_velocity_raw_jumia.parquet
  #   - ${project_dir}data/raw/loan_velocity_raw_mezzanine.parquet
  #   - ${project_dir}data/raw/loan_velocity_raw_ac_group.parquet
  #   - ${project_dir}data/raw/loan_velocity_raw_srds.parquet
  
  b_trigger_scoring:
    cmd: python ${project_dir}src/data/interswitch_uganda.py --config=params.yaml # --agent_id=3IS02066
    always_changed: true
    deps:
    - ${project_dir}src/data/interswitch_uganda.py
    # outs:
    # - ${project_dir}data/interim/loan_velocity_clean_bloom1.parquet